resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
  - name: ci
    type: git
    source:
      uri: https://github.com/flavorjones/chromedriver-helper/
      branch: master
      disable_ci_skip: true # always get the latest pipeline configuration

# TODO add a webhook
# - https://concourse-ci.org/resources.html#resource-webhook-token
# - https://github.com/flavorjones/chromedriver-helper/settings/hooks
  - name: chromedriver-helper-pr
    type: pull-request
    source:
      repository: flavorjones/chromedriver-helper
      access_token: {{github-repo-status-access-token}}
      ignore_paths:
        - concourse/

% ruby_version = RUBIES[:mri].last
jobs:
  - name: pr-pending
    public: true
    plan:
      - get: ci
      - get: chromedriver-helper-pr
        trigger: true
        version: every
      - put: chromedriver-helper-pr
        params: {path: chromedriver-helper-pr, status: PENDING}

  - name: ruby-<%= ruby_version %>
    public: true
    max_in_flight: 1
    plan:
      - get: ci
      - get: chromedriver-helper-pr
        trigger: true
        version: every
        passed: [pr-pending]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: chromedriver-helper-pr
              path: chromedriver-helper
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure:
          put: chromedriver-helper-pr
          params: {path: chromedriver-helper-pr, status: FAILURE}

  - name: pr-success
    public: true
    disable_manual_trigger: true
    plan:
      - get: chromedriver-helper-pr
        trigger: true
        version: every
        passed:
        - ruby-<%= ruby_version %>
      - put: chromedriver-helper-pr
        params: {path: chromedriver-helper-pr, status: SUCCESS}
